// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_transducer_RCPPEXPORTS_H_GEN_
#define RCPP_transducer_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace transducer {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("transducer", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("transducer", "_transducer_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in transducer");
            }
        }
    }

    inline arma::vec rbr_raw_to_pressure(const arma::vec& x, const arma::vec& calib) {
        typedef SEXP(*Ptr_rbr_raw_to_pressure)(SEXP,SEXP);
        static Ptr_rbr_raw_to_pressure p_rbr_raw_to_pressure = NULL;
        if (p_rbr_raw_to_pressure == NULL) {
            validateSignature("arma::vec(*rbr_raw_to_pressure)(const arma::vec&,const arma::vec&)");
            p_rbr_raw_to_pressure = (Ptr_rbr_raw_to_pressure)R_GetCCallable("transducer", "_transducer_rbr_raw_to_pressure");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rbr_raw_to_pressure(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(calib)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec rbr_raw_to_temperature(const arma::vec& x, const arma::vec& calib) {
        typedef SEXP(*Ptr_rbr_raw_to_temperature)(SEXP,SEXP);
        static Ptr_rbr_raw_to_temperature p_rbr_raw_to_temperature = NULL;
        if (p_rbr_raw_to_temperature == NULL) {
            validateSignature("arma::vec(*rbr_raw_to_temperature)(const arma::vec&,const arma::vec&)");
            p_rbr_raw_to_temperature = (Ptr_rbr_raw_to_temperature)R_GetCCallable("transducer", "_transducer_rbr_raw_to_temperature");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rbr_raw_to_temperature(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(calib)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec rbr_temperature_correction(const arma::vec& pressure, const arma::vec& temperature, const arma::vec& x) {
        typedef SEXP(*Ptr_rbr_temperature_correction)(SEXP,SEXP,SEXP);
        static Ptr_rbr_temperature_correction p_rbr_temperature_correction = NULL;
        if (p_rbr_temperature_correction == NULL) {
            validateSignature("arma::vec(*rbr_temperature_correction)(const arma::vec&,const arma::vec&,const arma::vec&)");
            p_rbr_temperature_correction = (Ptr_rbr_temperature_correction)R_GetCCallable("transducer", "_transducer_rbr_temperature_correction");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rbr_temperature_correction(Shield<SEXP>(Rcpp::wrap(pressure)), Shield<SEXP>(Rcpp::wrap(temperature)), Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline Rcpp::DatetimeVector rbr_times(const arma::vec& ev_tstamp, const arma::uvec& ev_index, double ti) {
        typedef SEXP(*Ptr_rbr_times)(SEXP,SEXP,SEXP);
        static Ptr_rbr_times p_rbr_times = NULL;
        if (p_rbr_times == NULL) {
            validateSignature("Rcpp::DatetimeVector(*rbr_times)(const arma::vec&,const arma::uvec&,double)");
            p_rbr_times = (Ptr_rbr_times)R_GetCCallable("transducer", "_transducer_rbr_times");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rbr_times(Shield<SEXP>(Rcpp::wrap(ev_tstamp)), Shield<SEXP>(Rcpp::wrap(ev_index)), Shield<SEXP>(Rcpp::wrap(ti)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::DatetimeVector >(rcpp_result_gen);
    }

    inline arma::mat rbr_calib_mult(arma::mat& x, const arma::mat& calib, const arma::vec& is_temp) {
        typedef SEXP(*Ptr_rbr_calib_mult)(SEXP,SEXP,SEXP);
        static Ptr_rbr_calib_mult p_rbr_calib_mult = NULL;
        if (p_rbr_calib_mult == NULL) {
            validateSignature("arma::mat(*rbr_calib_mult)(arma::mat&,const arma::mat&,const arma::vec&)");
            p_rbr_calib_mult = (Ptr_rbr_calib_mult)R_GetCCallable("transducer", "_transducer_rbr_calib_mult");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rbr_calib_mult(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(calib)), Shield<SEXP>(Rcpp::wrap(is_temp)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec density_temperature(const arma::vec& x) {
        typedef SEXP(*Ptr_density_temperature)(SEXP);
        static Ptr_density_temperature p_density_temperature = NULL;
        if (p_density_temperature == NULL) {
            validateSignature("arma::vec(*density_temperature)(const arma::vec&)");
            p_density_temperature = (Ptr_density_temperature)R_GetCCallable("transducer", "_transducer_density_temperature");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_density_temperature(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

}

#endif // RCPP_transducer_RCPPEXPORTS_H_GEN_
