# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rbr_raw_to_pressure
#'
#' @param x
#' @param calib
#'
#' @return
#' @export
#'
#' @examples
rbr_raw_to_pressure <- function(x, calib) {
    .Call('_transducer_rbr_raw_to_pressure', PACKAGE = 'transducer', x, calib)
}

#' rbr_raw_to_temperature
#'
#' @param x
#' @param calib
#'
#' @return
#' @export
#'
#' @examples
rbr_raw_to_temperature <- function(x, calib) {
    .Call('_transducer_rbr_raw_to_temperature', PACKAGE = 'transducer', x, calib)
}

#' rbr_temperature_correction
#'
#' @param pressure
#' @param temperature
#' @param x calibration constants
#'
#' @return
#' @export
#'
#' @examples
rbr_temperature_correction <- function(pressure, temperature, x) {
    .Call('_transducer_rbr_temperature_correction', PACKAGE = 'transducer', pressure, temperature, x)
}

#' rbr_times
#'
#' @param ev_tstamp
#' @param ev_index
#' @param ti
#'
#' @return
#' @export
#'
#' @examples
rbr_times <- function(ev_tstamp, ev_index, ti) {
    .Call('_transducer_rbr_times', PACKAGE = 'transducer', ev_tstamp, ev_index, ti)
}

#' rbr_calib_mult
#'
#' @param x
#' @param calib
#' @param is_temp
#'
#' @return
#' @export
#'
#' @examples
rbr_calib_mult <- function(x, calib, is_temp) {
    .Call('_transducer_rbr_calib_mult', PACKAGE = 'transducer', x, calib, is_temp)
}

#' @title  density_temperature
#'
#' @details This function estimates the density of water at a given temperature
#' using Kell's formulation. ITS-90
#'
#' @param x temperature
#'
#' @return
#' @export
#' @seealso \link{https://nvlpubs.nist.gov/nistpubs/jres/097/jresv97n3p335_A1b.pdf}
density_temperature <- function(x) {
    .Call('_transducer_density_temperature', PACKAGE = 'transducer', x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_transducer_RcppExport_registerCCallable', PACKAGE = 'transducer')
})
